type FieldType =
  | "boolean"
  | "date"
  | "datetime"
  | "json"
  | "markdown"
  | "number"
  | "string"
  | "string-array";

const collection = (
  slug: string,
  title: string,
  description: string,
  blockTypes: string[] = [],
  assetTypes: string[] = [],
) => ({
  collectionType: slug,
  config: { assetTypes, blockTypes },
  description,
  slug,
  title,
});

const field = (
  collectionSlug: string,
  key: string,
  label: string,
  fieldType: FieldType = "string",
  isRequired = false,
) => ({
  collectionSlug,
  fieldScope: "profile_data" as const,
  fieldType,
  isRequired,
  key,
  label,
});

const metadataField = (
  key: string,
  label: string,
  fieldType: FieldType = "string",
  collectionSlug: string | null = null,
) => ({
  collectionSlug,
  fieldScope: "metadata" as const,
  fieldType,
  isRequired: false,
  key,
  label,
});

const relation = (
  sourceCollectionSlug: string,
  key: string,
  label: string,
  targetCollectionSlugs: string[],
  cardinality: "many" | "one" = "one",
  isRequired = false,
) => ({
  cardinality,
  isRequired,
  key,
  label,
  sourceCollectionSlug,
  targetCollectionSlugs,
});

export const EXOCORPSE_CMS_SCHEMA = {
  collections: [
    collection(
      "about",
      "About Settings",
      "About page settings.",
      ["markdown"],
      ["image"],
    ),
    collection(
      "about-content",
      "About Content",
      "About cards, social links, DNI, and favorites.",
      ["markdown"],
    ),
    collection(
      "about-faqs",
      "About FAQs",
      "FAQ answers and username templates.",
    ),
    collection(
      "stories",
      "Stories",
      "Story universe records.",
      ["markdown"],
      ["image"],
    ),
    collection("worlds", "Worlds", "World records.", ["markdown"], ["image"]),
    collection(
      "characters",
      "Characters",
      "Character profiles and lore.",
      ["markdown"],
      ["image"],
    ),
    collection(
      "relationship-types",
      "Relationship Types",
      "Character relationship types.",
      ["markdown"],
    ),
    collection("outfit-types", "Outfit Types", "Character outfit types.", [
      "markdown",
    ]),
    collection("event-types", "Event Types", "Timeline event types.", [
      "markdown",
    ]),
    collection(
      "factions",
      "Factions",
      "Organizations and faction lore.",
      ["markdown"],
      ["image"],
    ),
    collection(
      "locations",
      "Locations",
      "World locations and geography.",
      ["markdown"],
      ["image"],
    ),
    collection(
      "location-gallery",
      "Location Gallery",
      "Location gallery images.",
      ["markdown"],
      ["image"],
    ),
    collection(
      "character-outfits",
      "Character Outfits",
      "Character outfits and references.",
      ["markdown"],
      ["image"],
    ),
    collection(
      "character-gallery",
      "Character Gallery",
      "Character gallery images.",
      ["markdown"],
      ["image"],
    ),
    collection(
      "character-relationships",
      "Character Relationships",
      "Content-bearing character relationship records.",
      ["markdown"],
    ),
    collection(
      "character-factions",
      "Character Factions",
      "Content-bearing faction memberships.",
      ["markdown"],
    ),
    collection(
      "character-locations",
      "Character Locations",
      "Content-bearing character location records.",
      ["markdown"],
    ),
    collection(
      "portfolio-art",
      "Portfolio Art",
      "Art portfolio entries.",
      ["markdown"],
      ["image"],
    ),
    collection(
      "portfolio-writing",
      "Portfolio Writing",
      "Writing portfolio entries.",
      ["markdown"],
      ["image"],
    ),
    collection(
      "portfolio-games",
      "Portfolio Games",
      "Game portfolio entries.",
      ["markdown"],
      ["image"],
    ),
    collection(
      "commission-services",
      "Commission Services",
      "Commission service offerings.",
      ["markdown"],
      ["image"],
    ),
    collection(
      "commission-addons",
      "Commission Addons",
      "Commission addons and price modifiers.",
    ),
    collection("commission-styles", "Commission Styles", "Commission styles.", [
      "markdown",
    ]),
    collection(
      "commission-pictures",
      "Commission Pictures",
      "Commission examples.",
      [],
      ["image"],
    ),
    collection(
      "commission-blacklist",
      "Commission Blacklist",
      "Public commission blacklist.",
    ),
    collection(
      "blog-posts",
      "Blog Posts",
      "Blog posts.",
      ["markdown"],
      ["image"],
    ),
    collection(
      "heaven-space-passages",
      "Heaven Space Passages",
      "Visual-novel passages.",
      ["markdown"],
    ),
    collection(
      "heaven-space-assets",
      "Heaven Space Assets",
      "Visual-novel assets.",
      [],
      ["image"],
    ),
    collection(
      "heaven-space-scenes",
      "Heaven Space Scenes",
      "Scene graph records.",
      ["scene-body"],
    ),
    collection(
      "heaven-space-scene-choices",
      "Heaven Space Scene Choices",
      "Content-bearing scene choices.",
    ),
    collection("timelines", "Timelines", "World timeline records.", [
      "markdown",
    ]),
    collection("events", "Events", "Timeline events.", ["markdown"], ["image"]),
    collection(
      "event-participants",
      "Event Participants",
      "Content-bearing event participants.",
      ["markdown"],
    ),
    collection(
      "event-factions",
      "Event Factions",
      "Content-bearing event faction records.",
      ["markdown"],
    ),
    collection("tags", "Tags", "Reusable content tags.", ["markdown"]),
    collection(
      "moodboards",
      "Moodboards",
      "Visual reference sets.",
      ["markdown"],
      ["image"],
    ),
    collection(
      "media-assets",
      "Media Assets",
      "Generic media library.",
      ["markdown"],
      ["image", "audio", "video", "document"],
    ),
  ],
  fieldDefinitions: [
    metadataField("sourceId", "Legacy source ID"),
    metadataField("sourceTable", "Legacy source table"),
    metadataField("deletedAt", "Deleted at", "datetime", "locations"),
    ...[
      "aboutUseHeading",
      "dniIntro",
      "dniTitle",
      "experiencesHeading",
      "faqIntro",
      "faqTitle",
      "favoritesHeading",
      "heroImageAlt",
      "heroName",
      "heroSubtitle",
      "moreInfoHeading",
      "socialsIntro",
      "socialsPrimaryUsername",
      "socialsSecondaryUsername",
      "socialsTitle",
    ].map((key) => field("about", key, key)),
    ...["colorKey", "iconKey", "section", "url", "variant"].map((key) =>
      field("about-content", key, key),
    ),
    field("about-content", "subtitle", "Subtitle"),
    field("about-content", "displayOrder", "Display order", "number"),
    field("about-content", "isFullWidth", "Full width", "boolean"),
    field("about-faqs", "display_order", "Display order", "number"),
    field("about-faqs", "faq_type", "FAQ type"),
    field("about-faqs", "question", "Question", "string", true),
    ...[
      "alias_description",
      "alias_primary",
      "alias_secondary",
      "brushes_paint_tool_sai_text",
      "brushes_procreate_text",
      "commissions_text",
      "created_at",
      "devices_text",
      "id",
      "programs_text",
      "social_display_name",
      "social_intro_text",
      "social_note_prefix",
      "social_note_suffix",
      "updated_at",
      "username_prefix_left",
      "username_prefix_right",
      "username_result",
      "username_template",
    ].map((key) => field("about-faqs", key, key)),
    field("stories", "isPublished", "Published", "boolean"),
    field("stories", "visibility", "Visibility"),
    ...["themePrimaryColor", "themeSecondaryColor", "themeTextColor"].flatMap(
      (key) => [
        field("stories", key, key),
        field("worlds", key, key),
        field("characters", key, key),
        field("factions", key, key),
      ],
    ),
    field("worlds", "population", "Population", "number"),
    field("worlds", "size", "Size"),
    field("worlds", "worldType", "World type"),
    ...[
      "abilities",
      "birthday",
      "build",
      "distinguishingFeatures",
      "eyeColor",
      "fanworkPolicy",
      "gender",
      "hairColor",
      "height",
      "nickname",
      "occupation",
      "personalitySummary",
      "pronouns",
      "quote",
      "skinTone",
      "species",
      "spotifyLink",
      "status",
      "weight",
    ].map((key) => field("characters", key, key)),
    field("characters", "age", "Age", "number"),
    field("characters", "colorPalette", "Color palette", "string-array"),
    field("relationship-types", "isMutual", "Mutual", "boolean"),
    field("relationship-types", "reverseName", "Reverse name"),
    ...["outfit-types", "event-types"].flatMap((slug) => [
      field(slug, "color", "Color"),
      field(slug, "icon", "Icon"),
      field(slug, "isDefault", "Default", "boolean"),
    ]),
    ...[
      "factionType",
      "foundingDate",
      "powerLevel",
      "primaryGoal",
      "reputation",
      "status",
    ].map((key) => field("factions", key, key)),
    field("factions", "memberCount", "Member count", "number"),
    ...["location-gallery", "character-gallery"].flatMap((slug) => [
      field(slug, "artistName", "Artist name"),
      field(slug, "artistUrl", "Artist URL"),
      field(slug, "displayOrder", "Display order", "number"),
    ]),
    field("character-outfits", "displayOrder", "Display order", "number"),
    field("character-outfits", "colorPalette", "Color palette"),
    field("character-outfits", "isDefault", "Default", "boolean"),
    field("character-gallery", "commissionDate", "Commission date", "date"),
    field("character-gallery", "isFeatured", "Featured", "boolean"),
    field("character-gallery", "tags", "Tags", "string-array"),
    ...["isCurrent", "joinDate", "leaveDate", "notes", "rank", "role"].map(
      (key) =>
        field(
          "character-factions",
          key,
          key,
          key === "isCurrent" ? "boolean" : "string",
        ),
    ),
    ...["portfolio-art", "portfolio-writing"].flatMap((slug) => [
      field(slug, "createdDate", "Created date", "date"),
      field(slug, "displayOrder", "Display order", "number"),
      field(slug, "isFeatured", "Featured", "boolean"),
      field(slug, "tags", "Tags", "string-array"),
      field(slug, "year", "Year", "number"),
    ]),
    field("portfolio-art", "artistName", "Artist name"),
    field("portfolio-art", "artistUrl", "Artist URL"),
    field("portfolio-writing", "wordCount", "Word count", "number"),
    field("portfolio-games", "gameUrl", "Game URL"),
    field("commission-services", "basePrice", "Base price", "number", true),
    field("commission-services", "commLink", "Commission link"),
    field("commission-services", "isActive", "Active", "boolean"),
    field("commission-addons", "isExclusive", "Exclusive", "boolean"),
    field("commission-addons", "percentage", "Percentage", "boolean"),
    field("commission-addons", "priceImpact", "Price impact", "number"),
    field("commission-pictures", "caption", "Caption"),
    field(
      "commission-pictures",
      "isPrimaryExample",
      "Primary example",
      "boolean",
    ),
    field("commission-pictures", "uploadedAt", "Uploaded at", "datetime"),
    field("commission-blacklist", "username", "Username", "string", true),
    field("commission-blacklist", "reasoning", "Reasoning", "markdown", true),
    field("commission-blacklist", "timestamp", "Timestamp", "datetime", true),
    field("blog-posts", "publishedAt", "Published at", "datetime"),
    field("heaven-space-passages", "name", "Passage name", "string", true),
    field("heaven-space-passages", "tags", "Tags", "string-array"),
    field("heaven-space-passages", "displayOrder", "Display order", "number"),
    field("heaven-space-passages", "passageKey", "Passage key"),
    field("heaven-space-assets", "displayOrder", "Display order", "number"),
    field("heaven-space-assets", "filename", "Filename", "string", true),
    field("heaven-space-scenes", "displayOrder", "Display order", "number"),
    field("heaven-space-scenes", "ending", "Ending"),
    field("heaven-space-scenes", "entryEffects", "Entry effects", "json"),
    field("heaven-space-scenes", "imageFilename", "Image filename"),
    field("heaven-space-scenes", "isStart", "Start scene", "boolean"),
    field("heaven-space-scenes", "legacyName", "Legacy name"),
    field("heaven-space-scenes", "legacySource", "Legacy source"),
    field("heaven-space-scenes", "mapPositionX", "Map X", "number"),
    field("heaven-space-scenes", "mapPositionY", "Map Y", "number"),
    field("heaven-space-scene-choices", "conditions", "Conditions", "json"),
    field(
      "heaven-space-scene-choices",
      "displayOrder",
      "Display order",
      "number",
    ),
    field("heaven-space-scene-choices", "effects", "Effects", "json"),
    field("heaven-space-scene-choices", "label", "Label", "string", true),
    field("heaven-space-scene-choices", "targetSceneSlug", "Target scene slug"),
    field("timelines", "color", "Color"),
    field("timelines", "endDate", "End date"),
    field("timelines", "eraName", "Era name"),
    field("timelines", "icon", "Icon"),
    field("timelines", "startDate", "Start date"),
    field("events", "casualties", "Casualties"),
    field("events", "color", "Color"),
    field("events", "date", "Date"),
    field("events", "dateYear", "Year", "number"),
    field("events", "duration", "Duration"),
    field("tags", "category", "Category"),
    field("tags", "color", "Color"),
    field("tags", "icon", "Icon"),
    field("tags", "useCount", "Use count", "number"),
  ],
  relationDefinitions: [
    relation("worlds", "story", "Story", ["stories"], "one", true),
    relation("characters", "worlds", "Worlds", ["worlds"], "many"),
    relation("stories", "tags", "Tags", ["tags"], "many"),
    relation("characters", "tags", "Tags", ["tags"], "many"),
    relation("outfit-types", "story", "Story", ["stories"]),
    relation("event-types", "story", "Story", ["stories"]),
    relation("factions", "world", "World", ["worlds"]),
    relation("factions", "parent", "Parent faction", ["factions"]),
    relation("locations", "world", "World", ["worlds"], "one", true),
    relation("locations", "parent", "Parent location", ["locations"]),
    relation(
      "location-gallery",
      "location",
      "Location",
      ["locations"],
      "one",
      true,
    ),
    relation(
      "character-outfits",
      "character",
      "Character",
      ["characters"],
      "one",
      true,
    ),
    relation("character-outfits", "type", "Outfit type", ["outfit-types"]),
    relation(
      "character-gallery",
      "character",
      "Character",
      ["characters"],
      "one",
      true,
    ),
    relation(
      "character-relationships",
      "character-a",
      "Character A",
      ["characters"],
      "one",
      true,
    ),
    relation(
      "character-relationships",
      "character-b",
      "Character B",
      ["characters"],
      "one",
      true,
    ),
    relation(
      "character-relationships",
      "type",
      "Relationship type",
      ["relationship-types"],
      "one",
      true,
    ),
    relation(
      "character-factions",
      "character",
      "Character",
      ["characters"],
      "one",
      true,
    ),
    relation(
      "character-factions",
      "faction",
      "Faction",
      ["factions"],
      "one",
      true,
    ),
    relation(
      "character-locations",
      "character",
      "Character",
      ["characters"],
      "one",
      true,
    ),
    relation(
      "character-locations",
      "location",
      "Location",
      ["locations"],
      "one",
      true,
    ),
    relation(
      "commission-services",
      "addons",
      "Addons",
      ["commission-addons"],
      "many",
    ),
    relation(
      "commission-styles",
      "service",
      "Service",
      ["commission-services"],
      "one",
      true,
    ),
    relation("commission-pictures", "service", "Service", [
      "commission-services",
    ]),
    relation("commission-pictures", "style", "Style", ["commission-styles"]),
    relation(
      "heaven-space-scene-choices",
      "scene",
      "Scene",
      ["heaven-space-scenes"],
      "one",
      true,
    ),
    relation("heaven-space-scene-choices", "next-scene", "Next scene", [
      "heaven-space-scenes",
    ]),
    relation("heaven-space-scenes", "image", "Image", ["heaven-space-assets"]),
    relation("timelines", "world", "World", ["worlds"], "one", true),
    relation("events", "timeline", "Timeline", ["timelines"], "one"),
    relation("events", "type", "Event type", ["event-types"]),
    relation("events", "world", "World", ["worlds"], "one", true),
    relation("events", "location", "Location", ["locations"]),
    relation("event-participants", "event", "Event", ["events"], "one", true),
    relation(
      "event-participants",
      "character",
      "Character",
      ["characters"],
      "one",
      true,
    ),
    relation("event-factions", "event", "Event", ["events"], "one", true),
    relation("event-factions", "faction", "Faction", ["factions"], "one", true),
    ...[
      "portfolio-art",
      "portfolio-writing",
      "portfolio-games",
      "blog-posts",
    ].map((slug) => relation(slug, "tags", "Tags", ["tags"], "many")),
    relation(
      "media-assets",
      "content",
      "Related content",
      [
        "about",
        "stories",
        "worlds",
        "characters",
        "factions",
        "locations",
        "portfolio-art",
        "portfolio-writing",
        "portfolio-games",
        "commission-services",
        "blog-posts",
        "heaven-space-scenes",
        "events",
        "moodboards",
      ],
      "many",
    ),
  ],
} as const;
