ALTER TABLE relationship_types
DROP COLUMN IF EXISTS created_by, DROP COLUMN IF EXISTS category, DROP COLUMN IF EXISTS slug, DROP COLUMN IF EXISTS icon, DROP COLUMN IF EXISTS is_default, DROP COLUMN IF EXISTS color, DROP COLUMN IF EXISTS story_id;

