name: Build Check

on:
  push:
    branches-ignore:
    - "dependabot/**"
    - "staging"
    - "production"
  workflow_dispatch:


jobs:
  build-check:
    name: Build Check
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun i

    - name: Run build
      run: bun run build
